@local=127.0.0.1
@port=3456


### end point
GET http://{{local}}:{{port}} HTTP/1.1
Content-Type: application/json

### CreateUsername
GET http://127.0.0.1:3456/CreateUsername HTTP/1.1
Content-Type: application/json

{
    "username" : "mikke"
}

### balance
GET http://{{local}}:{{port}}/balance/mike HTTP/1.1

###save monney
POST http://{{local}}:{{port}}/deposit/mike HTTP/1.1
Content-Type: application/json

{
    
    "amount": 999
}

###EchoServerPort
GET http://{{local}}:{{port}}/get HTTP/1.1
Content-Type: application/json

{
 "args": {
    "aaa": "bbb"
  },
  "headers": {
    "Accept": "*/*",
    "User-Agent": "curl/7.64.1",
    "X-Test-Headers": "haha"
  },
  "origin": "127.0.0.1",
  "url": "http://localhost:<EchoServerPort>/get?aaa=bbb"
}